/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

/**
 *
 * @author hp
 */
public class instant extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public instant() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookingroomcount = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        bookingfacility = new javax.swing.JComboBox();
        bookingname = new javax.swing.JTextField();
        bookingbedtype = new javax.swing.JComboBox();
        hostbtn = new javax.swing.JButton();
        bookingsubmitbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookingaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bookingphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bookingnid = new javax.swing.JTextField();
        bookingpaymentbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bookingindate = new org.jdesktop.swingx.JXDatePicker();
        bookingoutdate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Entry");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No of Room");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 160, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Out Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 260, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("In Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 210, 80, 30);

        bookingroomcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingroomcountActionPerformed(evt);
            }
        });
        jPanel1.add(bookingroomcount);
        bookingroomcount.setBounds(560, 160, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Extra Facilities");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 310, 100, 30);

        bookingfacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingfacilityActionPerformed(evt);
            }
        });
        jPanel1.add(bookingfacility);
        bookingfacility.setBounds(560, 310, 180, 30);

        bookingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingnameActionPerformed(evt);
            }
        });
        jPanel1.add(bookingname);
        bookingname.setBounds(150, 130, 160, 30);

        bookingbedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingbedtypeActionPerformed(evt);
            }
        });
        jPanel1.add(bookingbedtype);
        bookingbedtype.setBounds(560, 120, 180, 30);

        hostbtn.setBackground(new java.awt.Color(255, 255, 255));
        hostbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hostbtn.setText("<");
        hostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostbtnActionPerformed(evt);
            }
        });
        jPanel1.add(hostbtn);
        hostbtn.setBounds(10, 10, 60, 30);

        bookingsubmitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingsubmitbtn.setText("Submit");
        bookingsubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsubmitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookingsubmitbtn);
        bookingsubmitbtn.setBounds(370, 410, 160, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Bed Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 120, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 180, 80, 30);

        bookingaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingaddressActionPerformed(evt);
            }
        });
        jPanel1.add(bookingaddress);
        bookingaddress.setBounds(150, 180, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 230, 80, 30);

        bookingphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingphoneActionPerformed(evt);
            }
        });
        jPanel1.add(bookingphone);
        bookingphone.setBounds(150, 230, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("-----------------");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(630, 10, 100, 20);

        bookingnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingnidActionPerformed(evt);
            }
        });
        jPanel1.add(bookingnid);
        bookingnid.setBounds(150, 290, 160, 30);

        bookingpaymentbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingpaymentbtn.setText("Payment");
        bookingpaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingpaymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookingpaymentbtn);
        bookingpaymentbtn.setBounds(550, 410, 160, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("NID");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 290, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 10, 90, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("------------------");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(630, 50, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Payment Status:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 50, 110, 20);
        jPanel1.add(bookingindate);
        bookingindate.setBounds(560, 210, 180, 30);
        jPanel1.add(bookingoutdate);
        bookingoutdate.setBounds(560, 260, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingroomcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingroomcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingroomcountActionPerformed

    private void bookingfacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingfacilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingfacilityActionPerformed

    private void bookingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingnameActionPerformed

    private void bookingbedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbedtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbedtypeActionPerformed

    private void hostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostbtnActionPerformed
        // TODO add your handling code here
        service srvc=new service();
        srvc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hostbtnActionPerformed

    private void bookingsubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsubmitbtnActionPerformed
        new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookingsubmitbtnActionPerformed

    private void bookingaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingaddressActionPerformed

    private void bookingphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingphoneActionPerformed

    private void bookingnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingnidActionPerformed

    private void bookingpaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingpaymentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingpaymentbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingaddress;
    private javax.swing.JComboBox bookingbedtype;
    private javax.swing.JComboBox bookingfacility;
    private org.jdesktop.swingx.JXDatePicker bookingindate;
    private javax.swing.JTextField bookingname;
    private javax.swing.JTextField bookingnid;
    private org.jdesktop.swingx.JXDatePicker bookingoutdate;
    private javax.swing.JButton bookingpaymentbtn;
    private javax.swing.JTextField bookingphone;
    private javax.swing.JComboBox bookingroomcount;
    private javax.swing.JButton bookingsubmitbtn;
    private javax.swing.JButton hostbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
